services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/redis
    networks:
      - graph-service

  frequency:
    image: dsnp/instant-seal-node-with-deployed-schemas:latest
    # We need to specify the platform because it's the only image
    # built by Frequency at the moment, and auto-pull won't work otherwise
    platform: linux/amd64
    # Uncomment SEALING_MODE and SEALING_INTERVAL if you want to use interval sealing.
    # Other options you may want to add depending on your test scenario.
    # environment:
    #   - SEALING_MODE=interval
    #   - SEALING_INTERVAL=3
    #   - CREATE_EMPTY_BLOCKS=true
    # Uncomment below if you want to let the chain run and keep all of the historical blocks
    # command: --state-pruning=archive
    ports:
      - 9944:9944
    networks:
      - graph-service
    volumes:
      - chainstorage:/data

  graph-service-base:
    pull_policy: never
    image: graph-service:latest
    build:
      context: .
      dockerfile: dev.Dockerfile
      tags:
        - graph-service:latest

  api:
    pull_policy: never
    image: graph-service:latest
    command: ["npm", "run", "start:api:watch"]
    ports:
      - 3000:3000
    env_file:
      - .env.docker.dev
    volumes:
      - ./:/app
    depends_on:
      - redis
      - frequency
      - graph-service-base
    networks:
      - graph-service
    restart: on-failure

  worker:
    image: graph-service:latest
    pull_policy: never
    command: ["npm", "run", "start:worker:watch"]
    env_file:
      - .env.docker.dev
    volumes:
      - ./:/app
    depends_on:
      - redis
      - frequency
      - graph-service-base
    networks:
      - graph-service
    restart: on-failure

volumes:
  redis_data:
  chainstorage:
    external: false

networks:
  graph-service:
