x-graph-service-environment: &graph-service-environment
  FREQUENCY_URL: ws://frequency:9944
  REDIS_URL: redis://redis:6379
  QUEUE_HIGH_WATER: 1000
  API_PORT: 3000
  DEBOUNCE_SECONDS: 10
  CAPACITY_LIMIT: '{"type": "percentage", "value": 80 }'
  GRAPH_ENVIRONMENT_TYPE: Mainnet
  PROVIDER_ACCOUNT_SEED_PHRASE: '//Alice'
  PROVIDER_ID: 1
  RECONNECTION_SERVICE_REQUIRED: false
  WEBHOOK_FAILURE_THRESHOLD: 3
  WEBHOOK_RETRY_INTERVAL_SECONDS: 10
  HEALTH_CHECK_MAX_RETRY_INTERVAL_SECONDS: 10
  HEALTH_CHECK_MAX_RETRIES: 4

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/redis
    networks:
      - graph-service

  frequency:
    image: dsnp/instant-seal-node-with-deployed-schemas:latest
    # We need to specify the platform because it's the only image
    # built by Frequency at the moment, and auto-pull won't work otherwise
    platform: linux/amd64
    # Uncomment SEALING_MODE and SEALING_INTERVAL if you want to use interval sealing.
    # Other options you may want to add depending on your test scenario.
    environment:
      - SEALING_MODE=interval
      - SEALING_INTERVAL=1
    #   - CREATE_EMPTY_BLOCKS=true
    # Uncomment below if you want to let the chain run and keep all of the historical blocks
    # command: --state-pruning=archive
    ports:
      - 9944:9944
    networks:
      - graph-service
    volumes:
      - chainstorage:/data

  graph-service-base:
    pull_policy: never
    image: graph-service-dev:latest
    build:
      context: .
      dockerfile: dev.Dockerfile
      tags:
        - graph-service-dev:latest

  api:
    pull_policy: never
    image: graph-service-dev:latest
    ports:
      - 3000:3000
    command: ['npm', 'run', 'start:api:watch']
    environment:
      <<: [*graph-service-environment]
    volumes:
      - ./:/app
    depends_on:
      - redis
      - frequency
    networks:
      - graph-service
    restart: on-failure

  worker:
    image: graph-service-dev:latest
    pull_policy: never
    environment:
      <<: [*graph-service-environment]
    volumes:
      - ./:/app
    depends_on:
      - redis
      - frequency
      - graph-service-base
    networks:
      - graph-service
    restart: on-failure

volumes:
  redis_data:
  chainstorage:
    external: false

networks:
  graph-service:
