version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/redis
    networks:
      - graph-service-service
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  frequency:
    image: frequencychain/instant-seal-node:latest
    platform: linux/amd64
    ports:
      - 9944:9944
    profiles: ['', 'instant']
    networks:
      - graph-service-service
    container_name: frequency
    volumes:
      - chainstorage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9944/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  frequency-interval:
    image: frequencychain/instant-seal-node:latest
    command: --sealing=interval --sealing-interval 3 --sealing-create-empty-blocks
    ports:
      - 9944:9944
    profiles:
      - 'interval'
    networks:
      - graph-service-service
    container_name: frequency-interval-node
    volumes:
      - chainstorage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9944/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  frequency-manual:
    image: frequencychain/instant-seal-node:latest
    command: --sealing=manual
    ports:
      - 9944:9944
    profiles:
      - 'manual'
    networks:
      - graph-service-service
    container_name: frequency-manual-node
    volumes:
      - chainstorage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9944/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  graph-service-api:
    image: amplicalabs/graph-service-service:api-0.0.2-rc1
    platform: linux/amd64
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    environment:
      - START_PROCESS=api
      - REDIS_URL=redis://redis:6379
      - FREQUENCY_URL=http://frequency:9944
    volumes:
      - ./:/app
    depends_on:
      redis:
        condition: service_healthy
      frequency:
        condition: service_healthy
    networks:
      - graph-service-service
    container_name: graph-service-api
    profiles: ['instant']

  graph-service-worker:
    image: amplicalabs/graph-service-service:api-0.0.2-rc1
    platform: linux/amd64
    env_file:
      - .env.dev
    environment:
      - START_PROCESS=worker
      - REDIS_URL=redis://redis:6379
      - FREQUENCY_URL=http://frequency:9944
    volumes:
      - ./:/app
    depends_on:
      redis:
        condition: service_healthy
      frequency:
        condition: service_healthy
    networks:
      - graph-service-service
    profiles: ['instant'] 

volumes:
  redis_data:
  chainstorage:
    external: false

networks:
  graph-service-service:


